# Generated by Django 2.2.12 on 2020-05-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0002_fruit_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruit",
            name="image",
            field=models.FileField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
