# Generated by Django 2.0.1 on 2018-03-10 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.IntegerField()),
                ('sold_at', models.DateTimeField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.Fruit')),
            ],
        ),
    ]
